[project]
name = "tinkerbell"
version = "0.1.0"
authors=[
    {name="Aaiswarya Mishra",email="aaishwarymishra@gmail.com"}
]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "tqdm>=4.67.1",
]
